/**
 * 注册 Native Messaging Host：生成 host manifest + 写注册表（HKCU，无需管理员）
 * 用法：node native/register.js     （无需参数——扩展 ID 由 manifest 的固定 key 决定）
 */

'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

// 固定扩展 ID：由 extension/manifest.json 的 key（公钥）决定，任何机器都一致
// 算法：SHA256(DER 公钥)[前16字节] → 每个 nibble 映射到 a-p
const EXTENSION_ID = 'klnciafcpikgfonpgllfmldklfljolac';

const manifestPath = path.join(__dirname, 'com.coolbuy.launcher.json');
const launcherName = process.platform === 'win32' ? 'launch.bat' : 'launch.sh';
const launcherPath = path.join(__dirname, launcherName);
const manifest = {
  name: 'com.coolbuy.launcher',
  description: 'coolbuy 本地 Agent 启动器（Start 键控制进程生死）',
  path: launcherPath,
  type: 'stdio',
  allowed_origins: [`chrome-extension://${EXTENSION_ID}/`],
};
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

if (process.platform === 'win32') {
  registerWindows();
} else {
  registerUnix();
}

function registerWindows() {
  // launch.bat 必须纯 ASCII + CRLF。中文注释会被 cmd 按本地代码页误读，
  // 污染 Chrome native messaging 的 stdout 协议。
  fs.writeFileSync(launcherPath, [
    '@echo off',
    'rem coolbuy native messaging launcher (generated by register.js - keep ASCII only!)',
    `"${process.execPath}" "%~dp0coolbuy-launcher.js"`,
    '',
  ].join('\r\n'), 'ascii');

  // 同时注册 Chrome、Chromium、Edge 和 Brave，覆盖常见的 Chromium 浏览器。
  const keys = [
    'Google\\Chrome',
    'Chromium',
    'Microsoft\\Edge',
    'BraveSoftware\\Brave-Browser',
  ];
  const lines = ['Windows Registry Editor Version 5.00', ''];
  for (const browser of keys) {
    lines.push(
      `[HKEY_CURRENT_USER\\Software\\${browser}\\NativeMessagingHosts\\com.coolbuy.launcher]`,
      `@="${manifestPath.replace(/\\/g, '\\\\')}"`,
      '',
    );
  }
  const regFile = path.join(__dirname, 'coolbuy-launcher.reg');
  fs.writeFileSync(regFile, lines.join('\r\n'));
  try {
    execFileSync('reg', ['import', regFile], { stdio: 'inherit' });
  } finally {
    fs.rmSync(regFile, { force: true });
  }
  printDone(['Chrome', 'Edge', 'Chromium', 'Brave']);
}

function registerUnix() {
  const shellPath = launcherPath.replace(/"/g, '\\"');
  const nodePath = process.execPath.replace(/"/g, '\\"');
  fs.writeFileSync(launcherPath, [
    '#!/bin/sh',
    'exec "' + nodePath + '" "' + path.join(__dirname, 'coolbuy-launcher.js').replace(/"/g, '\\"') + '" "$@"',
    '',
  ].join('\n'), 'utf8');
  fs.chmodSync(launcherPath, 0o755);

  const browsers = process.platform === 'darwin' ? [
    ['Chrome', 'Library/Application Support/Google/Chrome'],
    ['Chromium', 'Library/Application Support/Chromium'],
    ['Edge', 'Library/Application Support/Microsoft Edge'],
    ['Brave', 'Library/Application Support/BraveSoftware/Brave-Browser'],
  ] : [
    ['Chrome', '.config/google-chrome'],
    ['Chromium', '.config/chromium'],
    ['Edge', '.config/microsoft-edge'],
    ['Brave', '.config/BraveSoftware/Brave-Browser'],
  ];

  for (const [, relativeDir] of browsers) {
    const dir = path.join(os.homedir(), relativeDir, 'NativeMessagingHosts');
    fs.mkdirSync(dir, { recursive: true });
    fs.copyFileSync(manifestPath, path.join(dir, 'com.coolbuy.launcher.json'));
  }
  printDone(browsers.map(([name]) => name));
}

function printDone(browsers) {
  console.log(`\n注册完成（${browsers.join(' / ')}）。`);
  console.log('完全重启浏览器后，按面板的 Start 即可拉起本地 Agent。');
}
