/**
 * 注册 Native Messaging Host：生成 host manifest + 写注册表（HKCU，无需管理员）
 * 用法：node native/register.js     （无需参数——扩展 ID 由 manifest 的固定 key 决定）
 */

'use strict';
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// 固定扩展 ID：由 extension/manifest.json 的 key（公钥）决定，任何机器都一致
// 算法：SHA256(DER 公钥)[前16字节] → 每个 nibble 映射到 a-p
const EXTENSION_ID = 'klnciafcpikgfonpgllfmldklfljolac';

const manifestPath = path.join(__dirname, 'com.coolbuy.launcher.json');
const manifest = {
  name: 'com.coolbuy.launcher',
  description: 'coolbuy 本地 Agent 启动器（Start 键控制进程生死）',
  path: path.join(__dirname, 'launch.bat'),
  type: 'stdio',
  allowed_origins: [`chrome-extension://${EXTENSION_ID}/`],
};
fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));

// launch.bat 同步重新生成：必须纯 ASCII + CRLF（cmd 按 GBK 解析 bat，
// 中文注释会被误读成命令，污染 native messaging 的 stdout 协议导致握手失败）；
// node 用绝对路径，不依赖 Chrome 子进程的 PATH 环境
fs.writeFileSync(path.join(__dirname, 'launch.bat'), [
  '@echo off',
  'rem coolbuy native messaging launcher (generated by register.js - keep ASCII only!)',
  `"${process.execPath}" "%~dp0coolbuy-launcher.js"`,
  '',
].join('\r\n'), 'ascii');

// 写注册表用 .reg 文件导入：避免路径含空格/引号时 reg add 命令行解析出错
const regFile = path.join(__dirname, 'coolbuy-launcher.reg');
const escaped = manifestPath.replace(/\\/g, '\\\\');
fs.writeFileSync(regFile, [
  'Windows Registry Editor Version 5.00',
  '',
  '[HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\com.coolbuy.launcher]',
  `@="${escaped}"`,
  '',
].join('\r\n'));
execSync(`reg import "${regFile}"`, { stdio: 'inherit' });
fs.unlinkSync(regFile);
console.log('\n注册完成。重启 Chrome 后，按面板的 Start 即可拉起本地 Agent。');
